### ISSUE TITLE
Use hf_transfer to speed up downloads from the Hub

### ISSUE THREAD

**Issue by severo** [huggingface/dataset-viewer#2525]
In /search, in particular

https://github.com/huggingface/hf_transfer/ or `HF_HUB_ENABLE_HF_TRANSFER` in huggingface_hub

**Comment by lhoestq** [comment]
I think it's still not enabled for some reason.

Maybe because it's setting the environment variable after `huggingface_hub` is imported. Indeed the `HF_HUB_ENABLE_HF_TRANSFER` variable in `huggingface_hub` is set [at import time](https://github.com/huggingface/huggingface_hub/blob/05585741416faf1ca5364da63c450ae56adbfb9b/src/huggingface_hub/constants.py#L159-L163) based on the environment variable. So setting the environment variable after the import may have no effect.

Let's set `HF_HUB_ENABLE_HF_TRANSFER=1` in the worker env template maybe ?

**Comment by AndreaFrancis** [comment]
Done by https://github.com/huggingface/dataset-viewer/pull/2615
